# =============================================================================
# Example 3: Multi-GPU Training Job
# =============================================================================
# This example shows multi-GPU training with AMD GPUs.
# Demonstrates distributed training capabilities.
# Note: This is a simplified example due to CRD limitations.
# =============================================================================

apiVersion: kaiwo.silogen.ai/v1alpha1
kind: KaiwoJob
metadata:
  name: multi-gpu-training-job
  annotations:
    kaiwo.ai/gpu-fraction: "1.0"        # Full GPU allocation
    kaiwo.ai/gpu-memory: "8000"         # Request 8GB GPU memory
spec:
  template:
    spec:
      containers:
      - name: training-worker
        image: amd/pytorch:rocm5.6
        resources:
          requests:
            cpu: 4
            memory: 8Gi
            amd.com/gpu: 2
          limits:
            cpu: 8
            memory: 16Gi
            amd.com/gpu: 2

# =============================================================================
# Usage:
# kubectl apply -f examples/kaiwojobs/03-multi-gpu-training-job.yaml
# kubectl get kaiwojobs
# kubectl logs job/multi-gpu-training-job
# =============================================================================
